import { test, expect } from '@playwright/test';

test('sign-up form verification', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Join Now' }).click();
  await page.getByLabel('First name*:').click();
  await page.getByLabel('First name*:').click();
  await page.getByLabel('First name*:').fill('8878787');
  await page.getByLabel('Last name*:').click();
  await page.getByLabel('Last name*:').fill('8787878');
  await page.getByPlaceholder('Enter phone number').click();
  await page.getByPlaceholder('Enter phone number').fill('+1 650 000 0000');
  await page.getByLabel('Email address*:').click();
  await page.getByLabel('Email address*:').fill('wobbly@lipaworld.com');
  await page.getByPlaceholder('DD').click();
  await page.getByPlaceholder('DD').fill('11');
  await page.getByPlaceholder('MM').click();
  await page.getByPlaceholder('MM').fill('1');
  await page.getByPlaceholder('YYYY').click();
  await page.getByPlaceholder('YYYY').fill('1911');
  await page.getByPlaceholder('MM').click();
  await page.getByPlaceholder('MM').fill('9');
  await page.getByPlaceholder('DD').click();
  await page.getByPlaceholder('DD').fill('11');
  await page.getByLabel('City*:').click();
  await page.getByLabel('City*:').fill('Jatropha');
  await page.getByLabel('Post code:').click();
  await page.getByLabel('Post code:').fill('10304');
  await page.getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Male', exact: true }).click();
  await page.getByLabel('Password*:').click();
  await page.getByLabel('Password*:').fill('000000');
  await page.locator('#confirm-password').click();
  await page.locator('#confirm-password').fill('000000');
  await page.getByRole('checkbox').uncheck();
  await page.getByRole('button', { name: 'Join Now' }).click();
  await page.getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Join Now' }).click();
  await page.getByText('Invalid characters found in').click();
  await page.getByLabel('Last name*:').click();
  await page.getByLabel('Last name*:').click();
  await page.getByLabel('Last name*:').fill("O'Brien van der Meer Nguyễn");
  await page.getByLabel('First name*:').click();
  await page.getByLabel('First name*:').fill('Zhané Jo-Delante8');
  await page.getByRole('button', { name: 'Join Now' }).click();
  await expect(page.getByText('Invalid characters found in')).toBeVisible();
  await page.getByLabel('First name*:').click();
  await page.getByLabel('First name*:').fill('Zhané Jo-Delante');
  await page.getByRole('button', { name: 'Join Now' }).click();
  await page.getByPlaceholder('DD').click();
  await page.getByPlaceholder('DD').fill('88');
  await page.getByPlaceholder('MM').click();
  await page.getByRole('button', { name: 'Join Now' }).click();
  await expect(page.getByText('Day must be between 1 and')).toBeVisible();
  await page.getByPlaceholder('DD').click();
  await page.getByPlaceholder('DD').fill('2');
  await page.getByPlaceholder('MM').click();
  await page.getByPlaceholder('MM').fill('9999');
  await page.getByRole('button', { name: 'Join Now' }).click();
  await expect(page.getByText('Month must be between 1 and')).toBeVisible();
  await page.getByPlaceholder('MM').click();
  await page.getByPlaceholder('MM').fill('2');
  await page.getByPlaceholder('YYYY').click();
  await page.getByPlaceholder('YYYY').fill('19112222');
  await page.getByRole('button', { name: 'Join Now' }).click();
  await expect(page.getByText('Year must be between 1900 and')).toBeVisible();
  await page.getByPlaceholder('YYYY').click();
  await page.getByPlaceholder('YYYY').fill('1980');
});
