import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Join Now' }).click();
  await page.getByRole('link', { name: 'Join Now' }).click();
  await page.getByRole('link', { name: 'Join Now' }).click();
  await page.goto('http://localhost:3000/register');
  await page.getByPlaceholder('DD').click();
  await page.getByPlaceholder('DD').fill('11');
  await page.getByPlaceholder('MM').click();
  await page.getByPlaceholder('MM').fill('11');
  await page.getByPlaceholder('YYYY').click();
  await page.getByPlaceholder('YYYY').fill('1922');
  await page.getByLabel('Email address*:').click();
  await page.getByLabel('Email address*:').fill('test@lipaworld.com');
  await page.getByPlaceholder('Enter phone number').click();
  await page.getByPlaceholder('Enter phone number').fill('+1 732 654 6657');
  await page.getByLabel('City*:').click();
  await page.getByLabel('City*:').fill('Texas');
  await page.getByLabel('Post code:').click();
  await page.getByLabel('Post code:').fill('17266');
  await page.getByLabel('​', { exact: true }).click();
  await page.getByLabel('​', { exact: true }).click();
  await page.getByLabel('​', { exact: true }).click();
  await page.getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Female' }).click();
  await page.getByLabel('Password*:').click();
  await page.getByLabel('Password*:').fill('P8ssword');
  await page.locator('#confirm-password').click();
  await page.locator('#confirm-password').fill('P8ssword');
  await page.getByRole('checkbox').check();
  await page.getByLabel('Last name*:').click();
  await page.getByLabel('Last name*:').fill("O'Brien , van der Meer, Nguyễn");
  await page.getByLabel('Last name*:').press('ArrowLeft');
  await page.getByLabel('Last name*:').press('ArrowLeft');
  await page.getByLabel('Last name*:').press('ArrowLeft');
  await page.getByLabel('Last name*:').press('ArrowLeft');
  await page.getByLabel('Last name*:').press('ArrowLeft');
  await page.getByLabel('Last name*:').press('ArrowLeft');
  await page.getByLabel('Last name*:').press('ArrowLeft');
  await page.getByLabel('Last name*:').press('ArrowLeft');
  await page.getByLabel('Last name*:').press('ArrowRight');
  await page.getByLabel('Last name*:').fill("O'Brien , van der Meer Nguyễn");
  await page.getByLabel('Last name*:').press('ArrowLeft');
  await page.getByLabel('Last name*:').press('ArrowLeft');
  await page.getByLabel('Last name*:').press('ArrowLeft');
  await page.getByLabel('Last name*:').press('ArrowLeft');
  await page.getByLabel('Last name*:').press('ArrowLeft');
  await page.getByLabel('Last name*:').press('ArrowLeft');
  await page.getByLabel('Last name*:').press('ArrowLeft');
  await page.getByLabel('Last name*:').press('ArrowLeft');
  await page.getByLabel('Last name*:').press('ArrowLeft');
  await page.getByLabel('Last name*:').press('ArrowLeft');
  await page.getByLabel('Last name*:').press('ArrowLeft');
  await page.getByLabel('Last name*:').press('ArrowRight');
  await page.getByLabel('Last name*:').fill("O'Brien van der Meer Nguyễn");
  await page.getByLabel('First name*:').click();
  await page.getByLabel('First name*:').fill('Zhané "John-Doe');
  await page.getByLabel('First name*:').press('ArrowLeft');
  await page.getByLabel('First name*:').press('ArrowLeft');
  await page.getByLabel('First name*:').press('ArrowLeft');
  await page.getByLabel('First name*:').press('ArrowLeft');
  await page.getByLabel('First name*:').press('ArrowLeft');
  await page.getByLabel('First name*:').press('ArrowRight');
  await page.getByLabel('First name*:').fill('Zhané John-Doe');
  await page.getByLabel('First name*:').press('ArrowRight');
  await page.getByLabel('First name*:').press('ArrowRight');
  await page.getByLabel('First name*:').press('ArrowRight');
  await page.getByLabel('First name*:').press('ArrowRight');
  await page.getByLabel('First name*:').press('ArrowRight');
  await page.getByLabel('First name*:').press('ArrowRight');
  await page.getByLabel('First name*:').press('ArrowRight');
  await page.getByLabel('First name*:').press('ArrowRight');
  await page.getByLabel('First name*:').fill('Zhané John-Doolean');
  await page.getByRole('button', { name: 'Join Now' }).click();
  await expect(page.getByText('Invalid characters found in')).toBeVisible();
});
